name: CI

on: [push, pull_request]

jobs:
  build:
    name: Test on ${{ matrix.os }} with python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install pip --upgrade
          python -m pip install pytest pytest-cov
      - name: Test with pytest
        run: |
          python -m pytest test_caesar_cipher.py --cov=caesar_cipher --cov-report xml
      - name: Coverage report
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          files: ./coverage.xml
